# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KSLSpyViewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='notify',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queryJSON',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='KSLSpyViewer.User'),
            preserve_default=False,
        ),
    ]
