# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KSLSpyViewer', '0004_auto_20171118_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
